import { randomUUID } from "node:crypto";
import {
  deserializeEvent,
  serializeEvent,
  type AnyHarnessEvent,
} from "@harness/events";
import {
  MAX_EVENT_PAGE_LIMIT,
  assertAppendOwnership,
  assertRecoveryLeaseExpired,
  assertOwnerId,
  assertSessionId,
  assertStatusTransition,
  decodeMetadata,
  decodeSessionJson,
  encodeMetadata,
  encodeSessionJson,
  eventPageBounds,
  SessionStoreError,
  type AuditEventPage,
  type AuditPageOptions,
  type CreateSessionOptions,
  type EventLog,
  type EventLogOptions,
  type EventPageOptions,
  type RecoverInterruptedResult,
  type SaveCheckpointOptions,
  type SequencedEvent,
  type SessionCheckpoint,
  type SessionEventPage,
  type SessionListing,
  type SessionMetadata,
  type SessionRecord,
  type SessionStatus,
  type SessionStore,
  type StatusTransitionResult,
} from "./store";

/** Minimal result shape implemented by node-postgres and deterministic fakes. */
export interface QueryResult<Row extends Record<string, unknown>> {
  rows: Row[];
  rowCount?: number | null;
}

/** Dependency-free query seam. A production adapter may wrap a pg PoolClient. */
export interface Queryable {
  query<Row extends Record<string, unknown> = Record<string, unknown>>(
    text: string,
    values?: readonly unknown[],
  ): Promise<QueryResult<Row>>;
}

/**
 * Must pin every callback query to one connection and commit or roll it back as
 * a unit. Supplying a pool's bare `query` method is not a transaction.
 */
export interface TransactionRunner {
  run<T>(operation: (transaction: Queryable) => Promise<T>): Promise<T>;
}

export interface PostgresSessionStoreOptions {
  queryable: Queryable;
  transactions: TransactionRunner;
  now?: () => string;
  newId?: (prefix: string) => string;
}

export const POSTGRES_SESSIONS_SCHEMA_VERSION = 2;

const CREATE_META_SQL = `/* sessions:migration-meta */
CREATE TABLE IF NOT EXISTS harness_session_store_meta (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
)`;

/** Ordered, append-only schema migrations; run through migratePostgresSessions. */
export const POSTGRES_SESSION_MIGRATIONS = [
  {
    version: 1,
    statements: [
      `/* sessions:migration-v1-sessions */
CREATE TABLE IF NOT EXISTS harness_sessions (
  session_id TEXT PRIMARY KEY,
  task_id TEXT,
  status TEXT NOT NULL CHECK (status IN ('active', 'closed', 'archived')),
  created_at TEXT NOT NULL,
  closed_at TEXT,
  metadata TEXT NOT NULL DEFAULT '{}',
  next_seq BIGINT NOT NULL DEFAULT 0 CHECK (next_seq >= 0),
  checkpoint_revision BIGINT NOT NULL DEFAULT 0 CHECK (checkpoint_revision >= 0),
  checkpoint_seq BIGINT CHECK (checkpoint_seq >= -1),
  checkpoint_payload TEXT,
  checkpoint_updated_at TEXT,
  CHECK (
    (checkpoint_revision = 0 AND checkpoint_seq IS NULL AND checkpoint_payload IS NULL AND checkpoint_updated_at IS NULL)
    OR
    (checkpoint_revision > 0 AND checkpoint_seq IS NOT NULL AND checkpoint_payload IS NOT NULL AND checkpoint_updated_at IS NOT NULL)
  )
)`,
      `/* sessions:migration-v1-events */
CREATE TABLE IF NOT EXISTS harness_events (
  global_seq BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 0 MINVALUE 0) PRIMARY KEY,
  session_id TEXT NOT NULL REFERENCES harness_sessions (session_id) ON DELETE RESTRICT,
  seq BIGINT NOT NULL CHECK (seq >= 0),
  event_id TEXT NOT NULL UNIQUE,
  at TEXT NOT NULL,
  actor TEXT,
  type TEXT NOT NULL,
  payload TEXT NOT NULL,
  ingested_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (session_id, seq)
)`,
      `/* sessions:migration-v1-session-events-index */
CREATE INDEX IF NOT EXISTS harness_events_session_seq_idx
ON harness_events (session_id, seq)`,
      `/* sessions:migration-v1-event-types-index */
CREATE INDEX IF NOT EXISTS harness_events_type_global_idx
ON harness_events (type, global_seq)`,
      `/* sessions:migration-v1-immutable-function */
CREATE OR REPLACE FUNCTION harness_reject_event_mutation()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'harness_events is append-only';
END;
$$`,
      `/* sessions:migration-v1-immutable-trigger */
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname = 'harness_events_immutable'
  ) THEN
    CREATE TRIGGER harness_events_immutable
    BEFORE UPDATE OR DELETE ON harness_events
    FOR EACH ROW EXECUTE FUNCTION harness_reject_event_mutation();
  END IF;
END;
$$`,
    ],
  },
  {
    version: 2,
    statements: [
      `/* sessions:migration-v2-global-sequence-table */
CREATE TABLE IF NOT EXISTS harness_event_global_sequence (
  singleton BOOLEAN PRIMARY KEY DEFAULT TRUE CHECK (singleton),
  next_global_seq BIGINT NOT NULL CHECK (next_global_seq >= 0)
)`,
      `/* sessions:migration-v2-global-sequence-drop-identity */
ALTER TABLE harness_events
ALTER COLUMN global_seq DROP IDENTITY IF EXISTS`,
      `/* sessions:migration-v2-global-sequence-initialize */
INSERT INTO harness_event_global_sequence (singleton, next_global_seq)
SELECT TRUE, COALESCE(MAX(global_seq) + 1, 0) FROM harness_events
ON CONFLICT (singleton) DO UPDATE
SET next_global_seq = GREATEST(
  harness_event_global_sequence.next_global_seq,
  EXCLUDED.next_global_seq
)`,
    ],
  },
] as const;

/** Apply known migrations under one transaction and reject a future schema. */
export async function migratePostgresSessions(
  queryable: Queryable,
  transactions: TransactionRunner,
): Promise<void> {
  await transactions.run(async (tx) => {
    // Serialize migrations from concurrent replicas without external tooling.
    await tx.query("/* sessions:migration-lock */ SELECT pg_advisory_xact_lock(684276431)");
    await tx.query(CREATE_META_SQL);
    const versionResult = await tx.query<{ value: string }>(
      "/* sessions:migration-version-read */ SELECT value FROM harness_session_store_meta WHERE key = 'schema_version'",
    );
    const rawVersion = versionResult.rows[0]?.value;
    const current = rawVersion === undefined ? 0 : Number(rawVersion);
    if (!Number.isSafeInteger(current) || current < 0 || current > POSTGRES_SESSIONS_SCHEMA_VERSION) {
      throw new SessionStoreError(
        "SESS_SCHEMA_VERSION",
        `unsupported Postgres sessions schema version: ${rawVersion ?? "missing"}`,
      );
    }
    for (const migration of POSTGRES_SESSION_MIGRATIONS) {
      if (migration.version <= current) continue;
      for (const statement of migration.statements) await tx.query(statement);
      await tx.query(
        `/* sessions:migration-version-write */
         INSERT INTO harness_session_store_meta (key, value) VALUES ('schema_version', $1)
         ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value`,
        [String(migration.version)],
      );
    }
  });
  // Keep the otherwise intentionally unused base seam visible in this helper's
  // signature: callers normally retain it for PostgresSessionStore itself.
  void queryable;
}

interface PostgresSessionRow extends Record<string, unknown> {
  session_id: string;
  task_id: string | null;
  status: string;
  created_at: string;
  closed_at: string | null;
  metadata: string;
  next_seq: string | number;
  checkpoint_revision: string | number;
  checkpoint_seq: string | number | null;
  checkpoint_payload: string | null;
  checkpoint_updated_at: string | null;
}

interface PostgresEventRow extends Record<string, unknown> {
  session_id: string;
  seq: string | number;
  global_seq: string | number;
  event_id: string;
  at: string;
  actor: string | null;
  type: string;
  payload: string;
}

function asSafeInteger(value: unknown, label: string, minimum = 0): number {
  const number = typeof value === "string" && /^-?\d+$/u.test(value)
    ? Number(value)
    : value;
  if (typeof number !== "number" || !Number.isSafeInteger(number) || number < minimum) {
    throw new SessionStoreError("SESS_INVALID_RECORD", `${label} is not a safe integer`);
  }
  return number;
}

function rowCount(result: QueryResult<Record<string, unknown>>): number {
  return result.rowCount ?? result.rows.length;
}

function recordFromRow(row: PostgresSessionRow | undefined, sessionId?: string): SessionRecord {
  if (!row) {
    throw new SessionStoreError(
      "SESS_NOT_FOUND",
      sessionId ? `session "${sessionId}" not found` : "session record not found",
    );
  }
  if (!(["active", "closed", "archived"] as const).includes(row.status as SessionStatus)) {
    throw new SessionStoreError("SESS_INVALID_RECORD", `invalid stored session status: ${row.status}`);
  }
  return {
    sessionId: row.session_id,
    taskId: row.task_id ?? undefined,
    status: row.status as SessionStatus,
    createdAt: row.created_at,
    closedAt: row.closed_at ?? undefined,
    metadata: decodeMetadata(row.metadata),
  };
}

function eventFromRow(row: PostgresEventRow): SequencedEvent {
  const event = deserializeEvent(row.payload);
  if (
    event.eventId !== row.event_id ||
    event.type !== row.type ||
    event.at !== row.at ||
    (event.actor ?? null) !== row.actor
  ) {
    throw new SessionStoreError(
      "SESS_INVALID_RECORD",
      `event projection does not match payload for ${row.session_id}/${String(row.seq)}`,
    );
  }
  return {
    sessionId: row.session_id,
    seq: asSafeInteger(row.seq, "event seq"),
    globalSeq: asSafeInteger(row.global_seq, "event global_seq"),
    event,
  };
}

function checkpointFromRow(
  row: PostgresSessionRow,
  sessionId: string,
): SessionCheckpoint | undefined {
  const revision = asSafeInteger(row.checkpoint_revision, "checkpoint revision");
  if (
    revision === 0 &&
    row.checkpoint_seq === null &&
    row.checkpoint_payload === null &&
    row.checkpoint_updated_at === null
  ) return undefined;
  if (
    revision === 0 ||
    row.checkpoint_seq === null ||
    row.checkpoint_payload === null ||
    row.checkpoint_updated_at === null
  ) {
    throw new SessionStoreError("SESS_INVALID_RECORD", "stored checkpoint is incomplete");
  }
  return {
    sessionId,
    revision,
    afterSeq: asSafeInteger(row.checkpoint_seq, "checkpoint seq", -1),
    payload: decodeSessionJson(row.checkpoint_payload, "session checkpoint"),
    updatedAt: row.checkpoint_updated_at,
  };
}

function canonicalEvent(event: AnyHarnessEvent): { event: AnyHarnessEvent; wire: string } {
  const decoded = deserializeEvent(serializeEvent(event));
  return { event: decoded, wire: serializeEvent(decoded) };
}

async function selectEventById(
  queryable: Queryable,
  eventId: string,
): Promise<PostgresEventRow | undefined> {
  return (await queryable.query<PostgresEventRow>(
    "/* sessions:event-by-id */ SELECT * FROM harness_events WHERE event_id = $1",
    [eventId],
  )).rows[0];
}

function resolveExistingEvent(
  row: PostgresEventRow,
  sessionId: string,
  wire: string,
): SequencedEvent {
  if (row.session_id !== sessionId || row.payload !== wire) {
    throw new SessionStoreError(
      "SESS_EVENT_CONFLICT",
      `eventId "${row.event_id}" is already used by a different event`,
    );
  }
  return eventFromRow(row);
}

async function lockSession(
  queryable: Queryable,
  sessionId: string,
): Promise<PostgresSessionRow> {
  const row = (await queryable.query<PostgresSessionRow>(
    "/* sessions:session-lock */ SELECT * FROM harness_sessions WHERE session_id = $1 FOR UPDATE",
    [sessionId],
  )).rows[0];
  if (!row) throw new SessionStoreError("SESS_NOT_FOUND", `session "${sessionId}" not found`);
  return row;
}

/**
 * Updating the singleton row both locks it and allocates the next value. The
 * lock is held through commit, so no later audit sequence can commit first.
 * Rollback also rolls back the increment, avoiding identity-style holes.
 */
async function allocateGlobalSequence(tx: Queryable): Promise<number> {
  const row = (await tx.query<{ global_seq: string | number }>(
    `/* sessions:global-seq-allocate */
     UPDATE harness_event_global_sequence
     SET next_global_seq = next_global_seq + 1
     WHERE singleton = TRUE
     RETURNING next_global_seq - 1 AS global_seq`,
  )).rows[0];
  if (!row) {
    throw new SessionStoreError(
      "SESS_INVALID_RECORD",
      "global event sequence row is missing; run sessions migrations",
    );
  }
  return asSafeInteger(row.global_seq, "allocated global event sequence");
}

async function appendWithLockedSession(
  tx: Queryable,
  session: PostgresSessionRow,
  sessionId: string,
  canonical: { event: AnyHarnessEvent; wire: string },
  options: EventLogOptions | undefined,
  ownershipTime?: string,
): Promise<SequencedEvent> {
  const duplicate = await selectEventById(tx, canonical.event.eventId);
  if (options) {
    if (ownershipTime === undefined) {
      throw new SessionStoreError("SESS_INVALID_RECORD", "owner lease clock is unavailable");
    }
    assertAppendOwnership(decodeMetadata(session.metadata), options.ownerId, ownershipTime);
  }
  if (duplicate) return resolveExistingEvent(duplicate, sessionId, canonical.wire);
  if (session.status !== "active") {
    throw new SessionStoreError(
      "SESS_CLOSED",
      `session "${sessionId}" is ${session.status}; new events cannot be appended`,
    );
  }
  const seq = asSafeInteger(session.next_seq, "session next_seq");
  const globalSeq = await allocateGlobalSequence(tx);
  const inserted = await tx.query<PostgresEventRow>(
    `/* sessions:event-insert */
     INSERT INTO harness_events
       (global_seq, session_id, seq, event_id, at, actor, type, payload)
     VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
     ON CONFLICT (event_id) DO NOTHING
     RETURNING *`,
    [
      globalSeq,
      sessionId,
      seq,
      canonical.event.eventId,
      canonical.event.at,
      canonical.event.actor ?? null,
      canonical.event.type,
      canonical.wire,
    ],
  );
  let stored = inserted.rows[0];
  if (!stored) {
    const raced = await selectEventById(tx, canonical.event.eventId);
    if (!raced) {
      throw new SessionStoreError("SESS_INVALID_RECORD", "event conflict did not return a row");
    }
    return resolveExistingEvent(raced, sessionId, canonical.wire);
  }
  if (asSafeInteger(stored.global_seq, "inserted global event sequence") !== globalSeq) {
    throw new SessionStoreError(
      "SESS_INVALID_RECORD",
      "inserted event did not retain its allocated global sequence",
    );
  }
  const advanced = await tx.query(
    `/* sessions:next-seq-advance */
     UPDATE harness_sessions SET next_seq = next_seq + 1
     WHERE session_id = $1 AND next_seq = $2`,
    [sessionId, seq],
  );
  if (rowCount(advanced) !== 1) {
    throw new SessionStoreError("SESS_INVALID_RECORD", "session sequence allocation lost its lock");
  }
  return eventFromRow(stored);
}

function sessionPage(rows: PostgresEventRow[], limit: number, cursor: number): SessionEventPage {
  const hasMore = rows.length > limit;
  const events = rows.slice(0, limit).map(eventFromRow);
  return { events, nextAfterSeq: events.at(-1)?.seq ?? cursor, hasMore };
}

function auditPage(rows: PostgresEventRow[], limit: number, cursor: number): AuditEventPage {
  const hasMore = rows.length > limit;
  const events = rows.slice(0, limit).map(eventFromRow);
  return {
    events,
    nextAfterGlobalSeq: events.at(-1)?.globalSeq ?? cursor,
    hasMore,
  };
}

class PostgresEventLog implements EventLog {
  constructor(
    private readonly store: PostgresSessionStore,
    private readonly sessionId: string,
    private readonly options?: EventLogOptions,
  ) {}

  async append(event: AnyHarnessEvent): Promise<number> {
    return (await this.appendSequenced(event)).seq;
  }

  appendSequenced(event: AnyHarnessEvent): Promise<SequencedEvent> {
    return this.store.appendEvent(this.sessionId, event, this.options);
  }

  read(options: EventPageOptions = {}): Promise<SessionEventPage> {
    return this.store.readSessionEvents(this.sessionId, options);
  }

  async slice(from: number, to?: number): Promise<AnyHarnessEvent[]> {
    const lo = Math.max(0, from);
    if (!Number.isSafeInteger(lo) || (to !== undefined && !Number.isSafeInteger(to))) {
      throw new SessionStoreError("SESS_INVALID_CURSOR", "slice bounds must be safe integers");
    }
    const hi = to === undefined ? undefined : Math.max(lo, to);
    const events: AnyHarnessEvent[] = [];
    let afterSeq = lo - 1;
    while (hi === undefined || afterSeq < hi - 1) {
      const remaining = hi === undefined ? MAX_EVENT_PAGE_LIMIT : hi - (afterSeq + 1);
      if (remaining <= 0) break;
      const page = await this.read({
        afterSeq,
        limit: Math.min(MAX_EVENT_PAGE_LIMIT, remaining),
      });
      events.push(...page.events.map((item) => item.event));
      if (!page.hasMore || page.events.length === 0) break;
      afterSeq = page.nextAfterSeq;
    }
    return events;
  }

  async size(): Promise<number> {
    return this.store.eventCount(this.sessionId);
  }
}

export class PostgresSessionStore implements SessionStore {
  private readonly queryable: Queryable;
  private readonly transactions: TransactionRunner;
  private readonly injectedNow?: () => string;
  private readonly newId: (prefix: string) => string;
  private closed = false;

  constructor(options: PostgresSessionStoreOptions) {
    this.queryable = options.queryable;
    this.transactions = options.transactions;
    this.injectedNow = options.now;
    this.newId = options.newId ?? ((prefix) => `${prefix}-${randomUUID()}`);
  }

  private assertOpen(): void {
    if (this.closed) {
      throw new SessionStoreError("SESS_INVALID_RECORD", "session store is closed");
    }
  }

  private async storageTime(queryable: Queryable): Promise<string> {
    if (this.injectedNow) return this.injectedNow();
    const row = (await queryable.query<{ now: string | Date }>(
      "/* sessions:storage-time */ SELECT CURRENT_TIMESTAMP AS now",
    )).rows[0];
    const value = row?.now;
    const time = value instanceof Date ? value.toISOString() : value;
    if (typeof time !== "string" || !Number.isFinite(Date.parse(time))) {
      throw new SessionStoreError("SESS_INVALID_RECORD", "database returned an invalid timestamp");
    }
    return time;
  }

  async currentTime(): Promise<string> {
    this.assertOpen();
    return this.storageTime(this.queryable);
  }

  async createSession(options: CreateSessionOptions = {}): Promise<SessionRecord> {
    this.assertOpen();
    const sessionId = options.sessionId ?? this.newId("sess");
    assertSessionId(sessionId);
    const metadata = encodeMetadata(options.metadata ?? {});
    const createdAt = options.createdAt ?? await this.currentTime();
    return this.transactions.run(async (tx) => {
      const inserted = await tx.query<PostgresSessionRow>(
        `/* sessions:session-create */
         INSERT INTO harness_sessions
           (session_id, task_id, status, created_at, metadata, next_seq, checkpoint_revision)
         VALUES ($1, $2, 'active', $3, $4, 0, 0)
         ON CONFLICT (session_id) DO NOTHING
         RETURNING *`,
        [sessionId, options.taskId ?? null, createdAt, metadata],
      );
      if (inserted.rows[0]) return recordFromRow(inserted.rows[0]);
      let existing = await lockSession(tx, sessionId);
      if (options.taskId && !existing.task_id) {
        const updated = await tx.query<PostgresSessionRow>(
          `/* sessions:session-task-fill */
           UPDATE harness_sessions SET task_id = $1
           WHERE session_id = $2 AND task_id IS NULL
           RETURNING *`,
          [options.taskId, sessionId],
        );
        existing = updated.rows[0] ?? existing;
      }
      return recordFromRow(existing, sessionId);
    });
  }

  async getSession(sessionId: string): Promise<SessionRecord> {
    this.assertOpen();
    assertSessionId(sessionId);
    const row = (await this.queryable.query<PostgresSessionRow>(
      "/* sessions:session-get */ SELECT * FROM harness_sessions WHERE session_id = $1",
      [sessionId],
    )).rows[0];
    return recordFromRow(row, sessionId);
  }

  async listSessions(): Promise<SessionListing[]> {
    this.assertOpen();
    const rows = (await this.queryable.query<PostgresSessionRow & { event_count: string | number }>(
      `/* sessions:session-list */
       SELECT s.*, COUNT(e.event_id) AS event_count
       FROM harness_sessions s
       LEFT JOIN harness_events e ON e.session_id = s.session_id
       GROUP BY s.session_id
       ORDER BY s.created_at DESC, s.session_id DESC`,
    )).rows;
    return rows.map((row) => ({
      ...recordFromRow(row),
      eventCount: asSafeInteger(row.event_count, "session event_count"),
    }));
  }

  eventLog(sessionId: string, options?: EventLogOptions): EventLog {
    this.assertOpen();
    assertSessionId(sessionId);
    if (options) assertOwnerId(options.ownerId);
    return new PostgresEventLog(
      this,
      sessionId,
      options ? { ownerId: options.ownerId } : undefined,
    );
  }

  async appendEvent(
    sessionId: string,
    event: AnyHarnessEvent,
    options?: EventLogOptions,
  ): Promise<SequencedEvent> {
    this.assertOpen();
    assertSessionId(sessionId);
    if (options) assertOwnerId(options.ownerId);
    const canonical = canonicalEvent(event);
    return this.transactions.run(async (tx) => {
      // Unowned service logs may resolve a committed retry without a lock.
      // Owner-bound logs always lock and validate their live lease first so a
      // stale worker cannot use idempotent success as a side-effect fence.
      if (!options) {
        const duplicate = await selectEventById(tx, canonical.event.eventId);
        if (duplicate) return resolveExistingEvent(duplicate, sessionId, canonical.wire);
      }
      const session = await lockSession(tx, sessionId);
      const ownershipTime = options ? await this.storageTime(tx) : undefined;
      return appendWithLockedSession(tx, session, sessionId, canonical, options, ownershipTime);
    });
  }

  async readSessionEvents(
    sessionId: string,
    options: EventPageOptions = {},
  ): Promise<SessionEventPage> {
    this.assertOpen();
    assertSessionId(sessionId);
    const { cursor, limit } = eventPageBounds(options.afterSeq, options.limit, "afterSeq");
    const exists = await this.queryable.query(
      "/* sessions:session-exists */ SELECT 1 AS found FROM harness_sessions WHERE session_id = $1",
      [sessionId],
    );
    if (exists.rows.length === 0) {
      throw new SessionStoreError("SESS_NOT_FOUND", `session "${sessionId}" not found`);
    }
    const rows = (await this.queryable.query<PostgresEventRow>(
      `/* sessions:event-page */
       SELECT * FROM harness_events
       WHERE session_id = $1 AND seq > $2
       ORDER BY seq
       LIMIT $3`,
      [sessionId, cursor, limit + 1],
    )).rows;
    return sessionPage(rows, limit, cursor);
  }

  async readAuditEvents(options: AuditPageOptions = {}): Promise<AuditEventPage> {
    this.assertOpen();
    const { cursor, limit } = eventPageBounds(
      options.afterGlobalSeq,
      options.limit,
      "afterGlobalSeq",
    );
    const rows = (await this.queryable.query<PostgresEventRow>(
      `/* sessions:audit-page */
       SELECT * FROM harness_events
       WHERE global_seq > $1
       ORDER BY global_seq
       LIMIT $2`,
      [cursor, limit + 1],
    )).rows;
    return auditPage(rows, limit, cursor);
  }

  async transitionSession(
    sessionId: string,
    expected: SessionStatus,
    next: SessionStatus,
    at?: string,
    options?: EventLogOptions,
  ): Promise<StatusTransitionResult> {
    this.assertOpen();
    assertSessionId(sessionId);
    if (options) assertOwnerId(options.ownerId);
    return this.transactions.run(async (tx) => {
      const row = await lockSession(tx, sessionId);
      const current = recordFromRow(row, sessionId);
      if (current.status !== expected) return { changed: false, record: current };
      assertStatusTransition(current.status, next);
      if (current.status === next) return { changed: false, record: current };
      const storageTime = options || at === undefined ? await this.storageTime(tx) : undefined;
      if (options) assertAppendOwnership(current.metadata, options.ownerId, storageTime!);
      const updated = await tx.query<PostgresSessionRow>(
        `/* sessions:session-transition */
         UPDATE harness_sessions
         SET status = $1,
             closed_at = CASE WHEN $1 = 'closed' THEN COALESCE(closed_at, $2) ELSE closed_at END
         WHERE session_id = $3 AND status = $4
         RETURNING *`,
        [next, at ?? storageTime!, sessionId, expected],
      );
      const changed = updated.rows[0];
      if (!changed) {
        throw new SessionStoreError("SESS_INVALID_RECORD", "locked session transition was lost");
      }
      return { changed: true, record: recordFromRow(changed, sessionId) };
    });
  }

  async setMetadata(
    sessionId: string,
    metadata: SessionMetadata,
    options?: EventLogOptions,
  ): Promise<SessionRecord> {
    this.assertOpen();
    assertSessionId(sessionId);
    if (options) assertOwnerId(options.ownerId);
    const wire = encodeMetadata(metadata);
    return this.transactions.run(async (tx) => {
      const current = await lockSession(tx, sessionId);
      if (current.status !== "active") {
        throw new SessionStoreError("SESS_CLOSED", `session "${sessionId}" is ${current.status}`);
      }
      if (options) {
        assertAppendOwnership(
          decodeMetadata(current.metadata),
          options.ownerId,
          await this.storageTime(tx),
        );
      }
      const updated = await tx.query<PostgresSessionRow>(
        `/* sessions:metadata-set */
         UPDATE harness_sessions SET metadata = $1
         WHERE session_id = $2 AND status = 'active'
         RETURNING *`,
        [wire, sessionId],
      );
      if (!updated.rows[0]) {
        throw new SessionStoreError("SESS_INVALID_RECORD", "locked metadata update was lost");
      }
      return recordFromRow(updated.rows[0], sessionId);
    });
  }

  async getCheckpoint(sessionId: string): Promise<SessionCheckpoint | undefined> {
    this.assertOpen();
    assertSessionId(sessionId);
    const row = (await this.queryable.query<PostgresSessionRow>(
      "/* sessions:checkpoint-get */ SELECT * FROM harness_sessions WHERE session_id = $1",
      [sessionId],
    )).rows[0];
    if (!row) throw new SessionStoreError("SESS_NOT_FOUND", `session "${sessionId}" not found`);
    return checkpointFromRow(row, sessionId);
  }

  async saveCheckpoint(
    sessionId: string,
    options: SaveCheckpointOptions,
  ): Promise<SessionCheckpoint> {
    this.assertOpen();
    assertSessionId(sessionId);
    const expected = asSafeInteger(options.expectedRevision, "expected checkpoint revision");
    const afterSeq = asSafeInteger(options.afterSeq, "checkpoint seq", -1);
    const payload = encodeSessionJson(options.payload, "session checkpoint");
    const updatedAt = options.updatedAt ?? await this.currentTime();
    return this.transactions.run(async (tx) => {
      const row = await lockSession(tx, sessionId);
      if (row.status !== "active") {
        throw new SessionStoreError("SESS_CLOSED", `session "${sessionId}" is ${row.status}`);
      }
      const currentRevision = asSafeInteger(row.checkpoint_revision, "checkpoint revision");
      const currentCheckpoint = checkpointFromRow(row, sessionId);
      // A retry of the immediately preceding write returns the durable value
      // without creating another revision. updatedAt is storage output, not an
      // idempotency input.
      if (
        currentRevision === expected + 1 &&
        currentCheckpoint?.afterSeq === afterSeq &&
        row.checkpoint_payload === payload
      ) {
        return currentCheckpoint;
      }
      if (currentRevision !== expected) {
        throw new SessionStoreError(
          "SESS_CHECKPOINT_CONFLICT",
          `checkpoint revision ${currentRevision} does not match expected ${expected}`,
        );
      }
      if (currentCheckpoint && afterSeq < currentCheckpoint.afterSeq) {
        throw new SessionStoreError(
          "SESS_CHECKPOINT_CONFLICT",
          `checkpoint seq ${afterSeq} is behind current seq ${currentCheckpoint.afterSeq}`,
        );
      }
      const nextSeq = asSafeInteger(row.next_seq, "session next_seq");
      if (afterSeq >= nextSeq) {
        throw new SessionStoreError(
          "SESS_INVALID_RECORD",
          `checkpoint seq ${afterSeq} is not yet durable`,
        );
      }
      const revision = expected + 1;
      const updated = await tx.query<PostgresSessionRow>(
        `/* sessions:checkpoint-save */
         UPDATE harness_sessions
         SET checkpoint_revision = $1, checkpoint_seq = $2,
             checkpoint_payload = $3, checkpoint_updated_at = $4
         WHERE session_id = $5 AND checkpoint_revision = $6
         RETURNING *`,
        [revision, afterSeq, payload, updatedAt, sessionId, expected],
      );
      if (!updated.rows[0]) {
        throw new SessionStoreError("SESS_CHECKPOINT_CONFLICT", "checkpoint compare-and-swap failed");
      }
      return {
        sessionId,
        revision,
        afterSeq,
        payload: decodeSessionJson(payload, "session checkpoint"),
        updatedAt,
      };
    });
  }

  async recoverInterrupted(
    sessionId: string,
    event: AnyHarnessEvent,
    closedAt?: string,
    expectedMetadata?: SessionMetadata,
  ): Promise<RecoverInterruptedResult> {
    this.assertOpen();
    assertSessionId(sessionId);
    const canonical = canonicalEvent(event);
    return this.transactions.run(async (tx) => {
      const row = await lockSession(tx, sessionId);
      const current = recordFromRow(row, sessionId);
      if (
        expectedMetadata !== undefined &&
        encodeMetadata(current.metadata) !== encodeMetadata(expectedMetadata)
      ) {
        throw new SessionStoreError(
          "SESS_RECOVERY_CONFLICT",
          `session "${sessionId}" owner metadata changed before recovery`,
        );
      }
      if (expectedMetadata !== undefined) {
        assertRecoveryLeaseExpired(current.metadata, await this.storageTime(tx));
      }
      const duplicate = await selectEventById(tx, canonical.event.eventId);
      const existing = duplicate
        ? resolveExistingEvent(duplicate, sessionId, canonical.wire)
        : undefined;
      if (current.status !== "active") {
        return { recovered: false, record: current, event: existing };
      }
      const stored = existing ?? await appendWithLockedSession(
        tx,
        row,
        sessionId,
        canonical,
        undefined,
      );
      const updated = await tx.query<PostgresSessionRow>(
        `/* sessions:recover-close */
         UPDATE harness_sessions
         SET status = 'closed', closed_at = COALESCE(closed_at, $1)
         WHERE session_id = $2 AND status = 'active'
         RETURNING *`,
        [closedAt ?? await this.storageTime(tx), sessionId],
      );
      if (!updated.rows[0]) {
        throw new SessionStoreError("SESS_INVALID_RECORD", "locked recovery transition was lost");
      }
      return {
        recovered: true,
        record: recordFromRow(updated.rows[0], sessionId),
        event: stored,
      };
    });
  }

  async eventCount(sessionId: string): Promise<number> {
    this.assertOpen();
    assertSessionId(sessionId);
    const exists = await this.queryable.query(
      "/* sessions:session-exists */ SELECT 1 AS found FROM harness_sessions WHERE session_id = $1",
      [sessionId],
    );
    if (exists.rows.length === 0) {
      throw new SessionStoreError("SESS_NOT_FOUND", `session "${sessionId}" not found`);
    }
    const row = (await this.queryable.query<{ count: string | number }>(
      "/* sessions:event-count */ SELECT COUNT(*) AS count FROM harness_events WHERE session_id = $1",
      [sessionId],
    )).rows[0];
    if (!row) throw new SessionStoreError("SESS_INVALID_RECORD", "event count query returned no row");
    return asSafeInteger(row.count, "event count");
  }

  close(): void {
    // Connection-pool ownership remains with the injected adapter.
    this.closed = true;
  }
}
