apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harness-postgres
  namespace: harness
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: postgres
      app.kubernetes.io/part-of: harness
