apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - resource-quota.yaml
  - limit-range.yaml
  - postgres
  - minio
  - sandbox-runner
  - control-plane
  - agent-server
  - networkpolicy
