apiVersion: v1
kind: LimitRange
metadata:
  name: harness
  namespace: harness
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 50m
        memory: 64Mi
        ephemeral-storage: 64Mi
      default:
        cpu: 500m
        memory: 512Mi
        ephemeral-storage: 256Mi
      max:
        cpu: "2"
        memory: 4Gi
        ephemeral-storage: 4Gi
