apiVersion: v1
kind: ResourceQuota
metadata:
  name: harness
  namespace: harness
spec:
  hard:
    requests.cpu: "16"
    requests.memory: 32Gi
    requests.ephemeral-storage: 8Gi
    requests.storage: 200Gi
    limits.cpu: "32"
    limits.memory: 64Gi
    limits.ephemeral-storage: 24Gi
    pods: "50"
    persistentvolumeclaims: "10"
    services: "20"
    count/jobs.batch: "100"
