apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harness-minio
  namespace: harness
spec:
  maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
      app.kubernetes.io/part-of: harness
