apiVersion: v1
kind: Service
metadata:
  name: harness-minio
  namespace: harness
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/component: artifact-storage
    app.kubernetes.io/part-of: harness
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: minio
    app.kubernetes.io/part-of: harness
  ports:
    - name: s3
      port: 9000
      targetPort: s3
      protocol: TCP
