apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: harness-control-plane
  namespace: harness
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: control-plane
      app.kubernetes.io/part-of: harness
