apiVersion: v1
kind: ServiceAccount
metadata:
  name: harness-control-plane
  namespace: harness
  labels:
    app.kubernetes.io/name: control-plane
    app.kubernetes.io/component: scheduler
    app.kubernetes.io/part-of: harness
automountServiceAccountToken: false
